url: https://www.lotuscosmeticsshop.com/
redisStoreUrl: redis://127.0.0.1:6379
scopeType: domain
overwrite: false
generateWACZ: false
workers: 1
headless: false
blockads: true
waitUntil: domcontentloaded
dryRun: false
redisStoreClean: true
collection: truyenhay
saveState: always
saveAllResources: true