version: "3.5"

services:
  crawler:
    image: ${REGISTRY}webrecorder/browsertrix-crawler:latest
    build:
      context: ./
    networks:
      - crawler_network
    volumes:
      - ./collections:/app/collections

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: tail -f /dev/null
    shm_size: 1gb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - crawler_network

networks:
  crawler_network:
    driver: bridge
