version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - crawler_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - crawler_network
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  crawler_network:
    driver: bridge