version: "3.5"

services:
  crawler:
    image: ${REGISTRY}webrecorder/browsertrix-crawler:latest
    build:
      context: ./

    volumes:
      - ./collections:/app/collections

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: tail -f /dev/null
    shm_size: 1gb
