version: "3.5"

services:
  crawler:
    image: ${REGISTRY}webrecorder/crawlertrix:latest
    build:
      context: ./
    networks:
      - crawler_network
    volumes:
      - ./collections:/app/collections

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: tail -f /dev/null
    shm_size: 1gb

networks:
  crawler_network:
    driver: bridge
