version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - crawler_network

networks:
  crawler_network:
    driver: bridge